server:
  port: 9001
  servlet:
    context-path: /api/v1/users

spring:
  application:
    name:UserService
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: pgAdmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev
